equinix/equinix-cloudevents

- jsonschema/catalog.json
- jsonschema/equinix/events/fabric/connections/ConnectionStatusEventData.json
* Add base path structure for a cloud event in equinix
* Add empty catalog file for further development of github webpages
> feat: Initial setup

- .github/workflows/create_tag_on_main_merge.yaml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
* Added GHA for SemVar version bump update
* Code Of Conduct Document Added
* CONTRIBUTING.md document Added
> Add GHA for version bump and Contribution document

- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/ChangeEvent.json
- jsonschema/equinix/fabric/v1/MetricAlert.json
- jsonschema/equinix/fabric/v1/MetricEvent.json
- scripts/generate_json_catalog.py
- scripts/generate_readme_event_catalog.py
- scripts/update_data_loader.py
Changes in PR:
- Updated all schemas to use name/description objects instead of just a list of event names
- Modified supporting scripts to be able to handle data schema formatting change
- Updated output format in README.md to produce tables inside of dropdowns to match the name/description data change
Output in GH Pages Looks Like the following after the change is merged:
> Update released and preview formats

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/MetricAlert.json
- jsonschema/equinix/fabric/v1/MetricEvent.json
> CXF-107131 update connection metric name, remove unused metric

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/MetricAlert.json
- jsonschema/equinix/fabric/v1/MetricEvent.json
> CXF-107129 update connection metric name

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/identity/v1/UserAuthenticationEvent.json
> PIM-5398: Adding logged out event to observability repo

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/ChangeEvent.json
> CXF-109139 add support for missing cloud events

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/time_service/v1/ChangeEvent.json
> CXF-109758 added cloud types

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/network_edge/v1/ChangeEvent.json
> NFV-30985 DLG and device attribute change events added

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/ChangeEvent.json
Routing Protocol
Routing Protocol Actions
Route Filter, Rules, Attachment
Route Aggregation, Rules, Attachment
> Alita Events April Release

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/MetricAlert.json
- jsonschema/equinix/fabric/v1/MetricEvent.json
- jsonschema/equinix/fabric/v1/MetroLatencyAlert.json
- jsonschema/equinix/fabric/v1/MetroLatencyMetric.json
> move metro latency metrics to MetricEvent.json and MetricAlert.json

- DataLoader.json
- scripts/update_data_loader.py
> Add Description Fields for Data Loader

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/ChangeEvent.json
> rename events for bgp session and policy attachment

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/ChangeEvent.json
- jsonschema/equinix/fabric/v1/MetricAlert.json
> release status updates

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/identity/v1/UserOrgLinkageEvent.json
> PIM-5762: Release status for orglinkage event updated to released

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/identity/v1/UserEmailChangedEvent.json
- [ X ] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md)
- [ X ] I certify that my `preview` and `released` lists for Events/Metrics/Alerts are correct
- [ X ] I certify that all Events/Metrics/Alerts in `released` are properly tested and ready for production
> PIM-5820: Added UserEmailChangedEvent to observability service

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/ChangeEvent.json
> CXF-111092: Update fcr renamed events to release

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/time_service/v1/ChangeEvent.json
> CXF-113571 Update EPT Cloud events to released

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/time_service/v1/ChangeEvent.json
- [V] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md)
- [V] I certify that my `preview` and `released` lists for Events/Metrics/Alerts are correct
- [V] I certify that all Events/Metrics/Alerts in `released` are properly tested and ready for production
> CXF-114303-Add new EPT state event

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/MetricAlert.json
> Add utilization alerts

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/iam/v1/ActionAuthorizedEvent.json
```
specversion: '1.0'
source: 'service:equinix/access'
id: 05b4b94d-f06d-4138-8aa5-dba712d12603
type: equinix.iam.principal.action.authorized
time: '2025-06-25T18:31:11.150Z'
severitytext: INFO
severitynumber: 9
equinixproject: 15a3d5e1-4974-4c7b-9a64-e2ab3d137401
equinixorganization: /15a3d5e1-4974-4c7b-9a64-e2ab3d137401
datacontenttype: application/json
datascheme: https://equinix.github.io/equinix-cloudevents/jsonschema/equinix/iam/v1/ActionAuthorizedEvent.json
subject: "principal:15a3d5e1-4974-4c7b-9a64-e2ab3d137401:okta-QQ47A5:00u61stiwref6D2rO697"
authtype: federated
authid: principal:15a3d5e1-4974-4c7b-9a64-e2ab3d137401:okta-QQ47A5:00u61stiwref6D2rO697
data:
message: "Action 'action:use/listAccessPolicies' authorized for principal …
```
> Add new IAM action-authorized event

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/MetricEvent.json
> Add utilization metrics

- DataLoader.json
- README.md
- jsonschema/catalog.json
- jsonschema/equinix/fabric/v1/MetricAlert.json
- jsonschema/equinix/fabric/v1/MetricEvent.json
> Release jitter avg metrics and alerts
